### ISSUE TITLE
Error during the compiling

### ISSUE THREAD

**Issue by simoneluconi** [colagrosso/avviso#10]
Arduino:1.6.5 (Windows 8.1), Scheda:"Arduino Uno"

Avviso\Avviso.cpp.o: In function `AvvisoClass::push(char*, char*, int)':
C:\Program Files (x86)\Arduino\libraries\Avviso/Avviso.cpp:109: undefined reference to`HTTPClient::HTTPClient(char_, unsigned char_)'
C:\Program Files (x86)\Arduino\libraries\Avviso/Avviso.cpp:118: undefined reference to `HTTPClient::getURI(char*, http_client_parameter*)'
C:\Program Files (x86)\Arduino\libraries\Avviso/Avviso.cpp:119: undefined reference to`HTTPClient::getLastReturnCode()'
C:\Program Files (x86)\Arduino\libraries\Avviso/Avviso.cpp:121: undefined reference to `HTTPClient::closeStream(__file*)'
collect2.exe: error: ld returned 1 exit status
Errore durante la compilazione

**Comment by colagrosso** [comment]
Hi, simoneluconi. I can't read Italian, but it looks like Avviso won't compile because it can't find the HTTPClient library. Download HTTPClient here:

https://github.com/interactive-matter/HTTPClient

and install HTTPClient.

**Comment by simoneluconi** [comment]
It works! Thanks! i I already had a http library, but probably it isn't compatible with Avviso.
