### ISSUE TITLE
exit status 1 Error compiling for board Arduino/Genuino Uno.

### ISSUE THREAD

**Issue by muzaf-dev** [colagrosso/avviso#11]
@colagrosso  did as ur tutorial, but when i compiling always shows an error, and couldn't debug 

Build options changed, rebuilding all
C:\Users\Muzaffar\AppData\Local\Temp\arduino_modified_sketch_97813\RingTheRedPhone.ino: In function 'void setup()':

C:\Users\Muzaffar\AppData\Local\Temp\arduino_modified_sketch_97813\RingTheRedPhone.ino:44:70: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

   Avviso.setApiKey("b3a8adf6fdc8ef961735719bf0bde0b06d1a1394b523d306");

```
                                                                  ^
```

C:\Users\Muzaffar\AppData\Local\Temp\arduino_modified_sketch_97813\RingTheRedPhone.ino:46:48: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

   Avviso.setApplicationName("Arduino Red Phone");

```
                                            ^
```

C:\Users\Muzaffar\AppData\Local\Temp\arduino_modified_sketch_97813\RingTheRedPhone.ino: In function 'void loop()':

C:\Users\Muzaffar\AppData\Local\Temp\arduino_modified_sketch_97813\RingTheRedPhone.ino:57:71: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

```
 int returnCode = Avviso.push("New event", "The sky is falling!", 0);

                                                                   ^
```

C:\Users\Muzaffar\AppData\Local\Temp\arduino_modified_sketch_97813\RingTheRedPhone.ino:57:71: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

In file included from C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp:27:0:

C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp: In member function '__file\* HTTPClient::getURI(char_, http_client_parameter_, http_client_parameter*)':

C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp:78:45: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]

   sendUriAndHeaders(result, this->hostName, PSTR("GET"), uri, parameters,

```
                                         ^
```

In file included from C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp:29:0:

C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.h:191:3: error:   initializing argument 3 of 'char HTTPClient::sendUriAndHeaders(__file_, char_, char_, char_, http_client_parameter_, http_client_parameter_)' [-fpermissive]

   sendUriAndHeaders(FILE\* stream, char\* hostName, char\* requestType, char\* uri,

   ^

In file included from C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp:27:0:

C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp: In member function '__file\* HTTPClient::postURI(char_, http_client_parameter_, char_, http_client_parameter_)':

C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp:107:45: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]

   sendUriAndHeaders(result, this->hostName, PSTR("POST"), uri, parameters,

```
                                         ^
```

In file included from C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp:29:0:

C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.h:191:3: error:   initializing argument 3 of 'char HTTPClient::sendUriAndHeaders(__file_, char_, char_, char_, http_client_parameter_, http_client_parameter_)' [-fpermissive]

   sendUriAndHeaders(FILE\* stream, char\* hostName, char\* requestType, char\* uri,

   ^

In file included from C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp:27:0:

C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp: In member function '__file\* HTTPClient::putURI(char_, http_client_parameter_, char_, http_client_parameter_)':

C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp:134:45: error: invalid conversion from 'const char_' to 'char_' [-fpermissive]

   sendUriAndHeaders(result, this->hostName, PSTR("PUT"), uri, parameters,

```
                                         ^
```

In file included from C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp:29:0:

C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.h:191:3: error:   initializing argument 3 of 'char HTTPClient::sendUriAndHeaders(__file_, char_, char_, char_, http_client_parameter_, http_client_parameter_)' [-fpermissive]

   sendUriAndHeaders(FILE\* stream, char\* hostName, char\* requestType, char\* uri,

   ^

C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp: In member function 'int HTTPClient::skipHeader(__file*)':

C:\Users\Muzaffar\Documents\Arduino\libraries\HTTPClient\HTTPClient.cpp:418:18: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]

```
       return NULL;

              ^
```

exit status 1
Error compiling for board Arduino/Genuino Uno.

**Comment by muzaffar622** [comment]
![2323423](https://cloud.githubusercontent.com/assets/19565126/15529421/28139ae2-2288-11e6-929e-038297db4ac9.jpg)

**Comment by muzaffar622** [comment]
![Uploading 2323423.jpg…]() @

**Comment by muzaf-dev** [comment]
i fixed the error. just download https://github.com/interactive-matter/HTTPClient and change the HTTPClient library. in documents/arduino/libraries/HTTPClient to downloaded files! thats it !!! Text message is come now ))

**Comment by divya97** [comment]
#include <MaxMatrix.h>
int DIN = 7;   // DIN pin of MAX7219 module
int CLK = 6;   // CLK pin of MAX7219 module
int CS = 5;    // CS pin of MAX7219 module
int maxInUse = 1;
MaxMatrix m(DIN, CS, CLK, maxInUse); 
char A[] = {4, 8,
            B01111110,
            B00010001,
            B00010001,
            B01111110,
           };
char B[] = {4, 8,
            B01111111,
            B01001001,
            B01001001,
            B00110110,
           };
char smile01[] = {8, 8,
                  B00111100,
                  B01000010,
                  B10010101,
                  B10100001,
                  B10100001,
                  B10010101,
                  B01000010,
                  B00111100
                 };
char smile02[] = {8, 8,
                  B00111100,
                  B01000010,
                  B10010101,
                  B10010001,
                  B10010001,
                  B10010101,
                  B01000010,
                  B00111100
                 };
char smile03[] = {8, 8,
                  B00111100,
                  B01000010,
                  B10100101,
                  B10010001,
                  B10010001,
                  B10100101,
                  B01000010,
                  B00111100
                 };
void setup() {
  m.init(); // MAX7219 initialization
  m.setIntensity(8); // initial led matrix intensity, 0-15
}
void loop() {
  // Seting the LEDs On or Off at x,y or row,column position
  m.setDot(6,2,true); 
  delay(1000);
  m.setDot(6,3,true);
  delay(1000);
  m.clear(); // Clears the display
  for (int i=0; i<8; i++){
    m.setDot(i,i,true);
    delay(300);
  }
  m.clear();
  // Displaying the character at x,y (upper left corner of the character)  
  m.writeSprite(2, 0, A);
  delay(1000);
  m.writeSprite(2, 0, B);
  delay(1000);
  m.writeSprite(0, 0, smile01);
  delay(1000);
  
  m.writeSprite(0, 0, smile02);
  delay(1000);
  
  m.writeSprite(0, 0, smile03);
  delay(1000);
  
  for (int i=0; i<8; i++){
    m.shiftLeft(false,false);
    delay(300);
  }
  m.clear();
}


when i was compiled it shows error:
exit status 1
Error compiling for board Arduino/Genuino Uno.
Even i changed show verbose output during **compilation**  it shows the same error.
