### ISSUE TITLE
Not showing up under File/Sketchbook

### ISSUE THREAD

**Issue by mattpackwood** [colagrosso/avviso#2]
I downloaded the Processing code and copied it so that all the files are under C:\Users\uswixmpac\Documents\Processing\libraries (i.e. so that RingTheRedPhone.pde is in C:\Users\uswixmpac\Documents\Processing\libraries\avviso\examples\RingTheRedPhone), started Processing, click on File/Sketchbook and nothing happens, am I missing something?

Matt

**Comment by colagrosso** [comment]
It sounds like you did everything right, Matt. I don't have a Windows
computer, but the directory you described is consistent with these
instructions on the Processing site:

http://wiki.processing.org/w/How_to_Install_a_Contributed_Library

Could you try to install a different Processing library and see if
that works? You could pick one of the contributed libraries from this
page:

http://processing.org/reference/libraries/

On Sun, Oct 2, 2011 at 5:21 PM, mattpackwood
reply@reply.github.com
wrote:

**Comment by colagrosso** [comment]
I'm closing this issue after not receiving a response. Feel free to re-open it if there are more updates.
