### ISSUE TITLE
I also would like to see Arduino 1.0 support

### ISSUE THREAD

**Issue by rhannink** [colagrosso/avviso#4]
Hello,

Are there any plans for porting to the Arduino 1.0 environment?
I tried to make some modifications myself 
- etherDNS and ethernetDHCP are now integrated in Ethernet
- #include <Arduino.h>

But still lot of other errors.

Maybe you can give me some additional directions so we can port to 1.0

With kind regards,

Remco

**Comment by colagrosso** [comment]
The latest commit supports Arduino 1.0. Thanks to those that worked on porting the dependent HTTPClient library to Arduino 1.0.

**Comment by rhannink** [comment]
Hello Mike,

Thanks for your fast response. I tried it and wrote a little SimpleProwl sketch and it compiles fine.
When I get home, I will try it on my Arduino.

Thanks again.

With kind regards,

Remco Hannink
Netherlands

Op 22 apr. 2012, om 21:05 heeft Mike Colagrosso het volgende geschreven:
