### ISSUE TITLE
Error 13822

### ISSUE THREAD

**Issue by techboywii** [colagrosso/avviso#5]
I have an Arduino Uno with an Ethernet Shield. Whenever I try to run the example sketch RingTheRedPhone, I get Error... Server Returned: 13822, My API key is set correctly, and my Ethernet Shield does have an internet connection. I can also still send notifications using GET with the web server and the Prowl API, but not with Avviso, Any help would be appreciated. Thanks.

**Comment by mikeMikeymike** [comment]
The bug is in the Avviso.cpp file in the library.
It will work if you turn on debug in that file (#define AVVISO_DEBUG 1)

To get it to work without being in debug mode, move this loop out of the debug section:
for (int i = 0; i < 4; i++) {
    prowlIpAddr[i] = remote_addr[i];
  }

**Comment by colagrosso** [comment]
Sorry about that mistake. The latest commit (5f112c03d8) fixes the issue.
