### ISSUE TITLE
Traditional Chinese characters

### ISSUE THREAD

**Issue by midastsai** [colagrosso/avviso#6]
How do I send a message using the Traditional Chinese characters?

**Comment by colagrosso** [comment]
Check the docs for Prowl or NMA, whichever one you're using. You'll have to
send the bytes in an encoding that service understands.

**Comment by midastsai** [comment]
Thanks for your reply. I use the Prowl, but still can't find the docs. Could you please indicate the location?

**Comment by colagrosso** [comment]
According to these docs:

http://www.prowlapp.com/api.php#methods

everything you send to Prowl should be in UTF-8 encoding.

In this example code:

https://github.com/colagrosso/avviso/blob/master/Arduino/libraries/Avviso/examples/RingTheRedPhone/RingTheRedPhone.ino#L81

which reads:

``` C++
int returnCode = Avviso.push("New event", "The sky is falling!", 0);
```

"New event" and "The sky is falling" are byte arrays. If you can construct valid byte arrays of UTF-8 characters, you can send them to Prowl. Note that depending on the character, it will require between 1 and 4 bytes. This website might help you construct the exact bytes you need:

http://www.utf8-chartable.de/

**Comment by colagrosso** [comment]
No followup in a year. Closing.
