### ISSUE TITLE
Sending push notification...Error. Server returned: 10496

### ISSUE THREAD

**Issue by Creautre** [colagrosso/avviso#7]
This my problem.

I am using an Arduino Nano and an W5100 Breakout board. The connection are made the same way that they are on an Arduino Uno. The regular Ethernet examples wich are implemented into the Arduino IDE are working.

When I am using the Nano board connected to processing i can send the notificiations. But when i use the W5100 Lan connection i get the error

"Sending push notification...Error. Server returned: 10496"

I inserted the API Key where it belongs, uncommented the Notify my android line and commented the Avviso.begin();

I hope you can tell me what the meaning of this error is.

Thx in advance

Martin

**Comment by colagrosso** [comment]
I don't know what 10496 means. That's not a valid HTTP return code. If you haven't already, can you set AVVISO_DEBUG to 1 here:

https://github.com/colagrosso/avviso/blob/master/Arduino/libraries/Avviso/Avviso.cpp#L38

and rerun it? The serial monitor should include more of Avviso's debug messages then.

I'm guessing the W5100 is not being initialized correctly. Does it get an IP address, gateway, and DNS in setup()? Posting the output of the serial monitor when running would show that:

https://github.com/colagrosso/avviso/blob/master/Arduino/libraries/Avviso/examples/RingTheRedPhone/RingTheRedPhone.ino

**Comment by Creautre** [comment]
Thanks for the quick response. The problem seemed to be the cabling. The program was in debug mode by default and i got my DHCP lease without a problem, the only problem was sending the push notification.

Today i wanted to show you the debug info and as i plugged in the Nano into my computer it had no connection to the W5100 chip anymore. The chip itself had no problem getting the DHCP lease... even with another Mac adress, so i was able to send data but not receive data.

I took my breadboard and pulled all the wires out and put them back in as they were before... and voila... it works, the connection between arduino and the W5100 and the push notification. It arrives with a delay of just 1 second , even on UMTS.

**Comment by colagrosso** [comment]
Great. Glad you got it working.
