### ISSUE TITLE
advise usb arduino error

### ISSUE THREAD

**Issue by losfastidios** [colagrosso/avviso#8]
This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
Arduino: 1.0.6 (Mac OS X), Board: "Arduino Uno"
RingTheRedPhone.ino: In function 'void setup()':
RingTheRedPhone:35: error: 'NOTIFY_MY_ANDROID' was not declared in this scope

**Comment by colagrosso** [comment]
NOTIFY_MY_ANDROID is declared here:

https://github.com/colagrosso/avviso/blob/master/Arduino/libraries/Avviso/Avviso.h#L26

Double-check that you have the Avviso library installed in the right Arduino folder. More info here:

https://github.com/colagrosso/avviso#getting-started-i-have-an-arduino-but-no-ethernet-shield

**Comment by colagrosso** [comment]
It looks like you're using a modified version of RingTheRedPhone.ino. Can you paste the sketch you are trying to compile? The error message in your original post mentions line 35, which doesn't make sense to me.

**Comment by colagrosso** [comment]
No response in 3 months.
